### PR TITLE
launch puppeteer without sandbox if sandboxed launch fails

### LINKED ISSUE #22: converted pdf file doesn't exist
When having a folder open and an unrelated markdown document it tries to save the PDF document to the open folder.

`a2dp_sink` is the folder opened currently. `solr-for-openaas.md` is the file I opened from a different folder. In my opinion it would be better to save the created PDF file to the source folder of the markdown document by default.

Now to the main issue:
The file MarkdownConverter is showing on the screenshot doesn't exist.

When clicking on `Open File`:

I also checked the folder where the markdown file is located, no PDF there either.

### PR DESCRIPTION
**Pull request by jkhsjdhjs**
Fix #22 

If Puppeteer fails to launch we'll catch the exception and try to launch it again without a sandbox.
This also adds the missing break to the platform switch case "linux".

### CODE REVIEW

**Comment by manuth** [comment]
I understand what you're trying to do.
Though I will adjust your code to integrate it with the way to code TypeScript and match it with my coding-style.

Hope you don't mind it.

Thanks for your contribution and thanks for using MarkdownConverter!

**Comment by jkhsjdhjs** [comment]
Okay, I'm interested in how you'll adjust it.

**Comment by manuth** [comment]
Alright - it may take a while since github is ducking up a lil atm. :joy:

**Comment by manuth** [comment]
Alright!
I just reworked it for a little - could you please try it out and check whether it's working out?
I can create a `.vsix`-package if you need one.

Thanks for your help

**Comment by jkhsjdhjs** [comment]
Yes, it works!
And it also shows an error message when the fallback launch fails:

**Comment by manuth** [comment]
Eww looks pretty ugly - but at least it's working :'D
I'll merge it asap - it will be part of the next release ^^

**Pull request merged**
